services:
  # Backend API Service
  - type: web
    name: varixscan-backend
    runtime: python
    buildCommand: "cd backend && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: starter
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: PORT
        value: "10000"
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      # Add your actual environment variables here
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY  
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Service (optional - you can also deploy separately)
  - type: web
    name: varixscan-frontend
    runtime: node
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    plan: starter
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"
      - key: NEXT_PUBLIC_API_URL
        value: "https://varixscan-backend.onrender.com"
      # Add your frontend environment variables
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
